# Generated by Django 2.0 on 2018-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='姓名')),
                ('sex', models.CharField(max_length=5, null=True, verbose_name='性别')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='电话')),
            ],
        ),
    ]
