# Generated by Django 2.0 on 2018-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('sales_type', models.CharField(max_length=50, verbose_name='销售类型')),
                ('store_name', models.CharField(max_length=200, verbose_name='店面名称')),
                ('order_state', models.CharField(max_length=50, verbose_name='订单状态')),
                ('payment_state', models.CharField(max_length=50, verbose_name='支付状态')),
                ('start_time', models.DateTimeField(verbose_name='下单时间')),
                ('order_time', models.DateTimeField(verbose_name='支付时间')),
                ('business_time', models.DateTimeField(verbose_name='营业时间')),
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='单据号')),
                ('order_id_old', models.CharField(max_length=200, verbose_name='原单据号')),
                ('area', models.CharField(max_length=50, verbose_name='区域')),
                ('desk_number', models.CharField(max_length=50, verbose_name='桌台号')),
                ('repast_number', models.IntegerField(verbose_name='就餐人数')),
                ('customer_name', models.CharField(max_length=150, verbose_name='顾客姓名')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='顾客电话')),
                ('customer_sex', models.CharField(max_length=5, verbose_name='顾客性别')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='收货人姓名')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('repast_type', models.CharField(max_length=50, verbose_name='就餐类型')),
                ('waiter_name', models.CharField(max_length=150, verbose_name='服务员姓名')),
                ('cash_terminal', models.CharField(max_length=50, verbose_name='收银终端')),
                ('operator_name', models.CharField(max_length=150, verbose_name='操作人姓名')),
                ('order_source', models.CharField(max_length=100, verbose_name='订单来源')),
                ('dispatching_state', models.CharField(max_length=50, verbose_name='配送状态')),
                ('dispatchinger', models.CharField(max_length=50, verbose_name='配送方')),
                ('dispatching_address', models.CharField(max_length=200, verbose_name='配送地址')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='订单金额(含押金)')),
                ('goods_money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品总额')),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='附加费')),
                ('dispatching_money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='配送费')),
                ('discount_summary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='优惠总额')),
                ('should_payment', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='应付金额')),
                ('actual_payment', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='实付金额')),
                ('should_get', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='应收金额')),
                ('actual_get', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='实收金额')),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='退款')),
                ('diposit_receive', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='押金')),
                ('diposit_return', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='押金')),
                ('diposit_over', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='押金溢收')),
                ('ceil_over', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='四舍五入')),
                ('floor_over', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='抹零')),
                ('payment_over', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='支付溢收')),
                ('over_summary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='损溢小计')),
                ('boss_consumption', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='老板消费')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='优惠券')),
                ('stored_value_card', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='储值卡')),
                ('landlady_consumption', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='老板娘消费')),
                ('weixin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='微信')),
                ('bank_card', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='银行卡')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现金')),
            ],
        ),
    ]
