# Generated by Django 2.0 on 2018-04-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0003_customer_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_management',
            fields=[
                ('area_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='区域')),
                ('area_customers_sum', models.IntegerField(verbose_name='区域容纳人数')),
                ('desk_number', models.CharField(max_length=50, null=True, verbose_name='桌台号')),
            ],
        ),
        migrations.CreateModel(
            name='cash_terminal',
            fields=[
                ('cash_terminal_model', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='收银终端型号')),
            ],
        ),
        migrations.CreateModel(
            name='diposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diposit_receive', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='收押金')),
                ('diposit_return', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='退押金')),
                ('diposit_over', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='押金溢收')),
                ('ceil_over', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='四舍五入')),
                ('floor_over', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='抹零')),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='单据号')),
                ('order_type', models.CharField(max_length=50, null=True, verbose_name='订单类型')),
                ('order_status', models.CharField(max_length=50, null=True, verbose_name='订单状态')),
                ('start_time', models.DateTimeField(null=True, verbose_name='下单时间')),
                ('business_time', models.DateField(null=True, verbose_name='营业时间')),
                ('order_source', models.CharField(max_length=100, null=True, verbose_name='订单来源')),
                ('cash_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.cash_terminal')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.customer_info')),
                ('diposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.diposit')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='mydashboard.waiter_info')),
            ],
        ),
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payment_state', models.CharField(max_length=50, null=True, verbose_name='支付状态')),
                ('order_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('should_payment', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='应付金额')),
                ('actual_payment', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='实付金额')),
                ('should_get', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='应收金额')),
                ('actual_get', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='实收金额')),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='退款')),
                ('payment_over', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='支付溢收')),
                ('over_summary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='损溢小计')),
            ],
        ),
        migrations.CreateModel(
            name='order_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='订单金额(含押金)')),
                ('goods_money', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='商品总额')),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='附加费')),
                ('dispatching_money', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='配送费')),
                ('discount_summary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='优惠总额')),
            ],
        ),
        migrations.CreateModel(
            name='payment_methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_consumption', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='老板消费')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='优惠券')),
                ('stored_value_card', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='储值卡')),
                ('landlady_consumption', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='老板娘消费')),
                ('weixin', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='微信')),
                ('bank_card', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='银行卡')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='现金')),
            ],
        ),
        migrations.CreateModel(
            name='receiver_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.person')),
            ],
        ),
        migrations.CreateModel(
            name='repast_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repast_number', models.IntegerField(null=True, verbose_name='就餐人数')),
                ('repast_type', models.CharField(max_length=50, null=True, verbose_name='就餐类型')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.area_management')),
            ],
        ),
        migrations.CreateModel(
            name='sender_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.person')),
            ],
        ),
        migrations.CreateModel(
            name='shipping_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='配送状态')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='配送地址')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.sender_info')),
            ],
        ),
        migrations.CreateModel(
            name='store_info',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='店面名称')),
            ],
        ),
        migrations.AddField(
            model_name='order_payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.payment_methods'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='order_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.order_price'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.order_payment'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.receiver_info'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='repast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.repast_info'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='shipping_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.shipping_info'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.store_info'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydashboard.waiter_info'),
        ),
    ]
