# Generated by Django 2.0 on 2018-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0004_auto_20180306_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='order_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='订单金额(含押金)'),
        ),
    ]
