# Generated by Django 2.0 on 2018-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0005_auto_20180306_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='actual_payment',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='discount_summary',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='优惠总额'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='dispatching_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='配送费'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='附加费'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='goods_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品总额'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='order_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单金额(含押金)'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='should_payment',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='应付金额'),
        ),
    ]
