# Generated by Django 2.0 on 2018-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0006_auto_20180306_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='actual_get',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='实收金额'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='area',
            field=models.CharField(max_length=50, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='bank_card',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='银行卡'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='boss_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='老板消费'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='现金'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='ceil_over',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='四舍五入'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='coupon',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='diposit_over',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='押金溢收'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='diposit_receive',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='diposit_return',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='押金'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='floor_over',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='抹零'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='landlady_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='老板娘消费'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='over_summary',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='损溢小计'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='payment_over',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付溢收'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='refunds',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='退款'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='should_get',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='应收金额'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='stored_value_card',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='储值卡'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='weixin',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='微信'),
        ),
    ]
